# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollBuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='버프 수치')),
            ],
        ),
        migrations.CreateModel(
            name='DollBuffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='버프 종류')),
            ],
        ),
        migrations.CreateModel(
            name='DollRank',
            fields=[
                ('num_star', models.IntegerField(primary_key=True, serialize=False, verbose_name='별 개수')),
                ('name', models.CharField(max_length=20, verbose_name='등급 이름')),
            ],
        ),
        migrations.CreateModel(
            name='DollSkillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='스킬 이름')),
                ('skill_description', models.TextField(verbose_name='스킬 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
            ],
        ),
        migrations.CreateModel(
            name='TacticalDoll',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('doll_description', models.TextField(verbose_name='설명')),
                ('doll_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='번호')),
                ('weapon_name', models.CharField(max_length=30, verbose_name='실제 총기명')),
                ('skill_pre_cooldown', models.IntegerField(verbose_name='스킬 사용 대기시간')),
                ('skill_cooldown', models.IntegerField(verbose_name='스킬 재사용 대기시간')),
                ('skill_duration', models.IntegerField(verbose_name='스킬 지속시간')),
                ('skill_value', models.IntegerField(verbose_name='스킬 수치')),
                ('buff_range', models.CharField(max_length=9, verbose_name='버프 범위')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('name_ko', models.CharField(blank=True, max_length=30, verbose_name='한글 이름')),
                ('name_en', models.CharField(blank=True, max_length=30, verbose_name='영문 이름')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, verbose_name='총기 종류')),
            ],
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='buff_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buff_target', to='girlsfrontlineDBWeb.WeaponType', verbose_name='버프 대상'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='buff_type',
            field=models.ManyToManyField(to='girlsfrontlineDBWeb.DollBuff'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='illustrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.Illustrator', verbose_name='일러스트'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.DollRank', verbose_name='등급'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='skill_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.DollSkillType', verbose_name='스킬명'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.VoiceActor', verbose_name='성우'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='weapon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_type', to='girlsfrontlineDBWeb.WeaponType', verbose_name='총기 종류'),
        ),
        migrations.AddField(
            model_name='dollskilltype',
            name='weapon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.WeaponType', verbose_name='총기 종류'),
        ),
        migrations.AddField(
            model_name='dollbuff',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.DollBuffType', verbose_name='버프 종류'),
        ),
    ]
