# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girlsfrontlineDBWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tacticaldoll',
            old_name='doll_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tacticaldoll',
            old_name='doll_num',
            new_name='num',
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='img_destroyed',
            field=models.ImageField(null=True, upload_to='', verbose_name='중상 이미지'),
        ),
        migrations.AddField(
            model_name='tacticaldoll',
            name='img_normal',
            field=models.ImageField(null=True, upload_to='', verbose_name='기본 이미지'),
        ),
        migrations.AlterField(
            model_name='tacticaldoll',
            name='buff_type',
            field=models.ManyToManyField(to='girlsfrontlineDBWeb.DollBuff', verbose_name='버프 종류'),
        ),
    ]
