# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girlsfrontlineDBWeb', '0002_auto_20171106_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='name',
            field=models.CharField(max_length=3, verbose_name='총기 종류'),
        ),
    ]
