# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girlsfrontlineDBWeb', '0003_auto_20171107_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacticaldoll',
            name='buff_type',
        ),
        migrations.AddField(
            model_name='dollbuff',
            name='doll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='girlsfrontlineDBWeb.TacticalDoll', verbose_name='전술 인형'),
        ),
    ]
